export const ADD_QUESTION_INIT = 'ADD_QUESTION_INIT';
export const ADD_QUESTION_START = 'ADD_QUESTION_START';
export const ADD_QUESTION_SUCCESS  = 'ADD_QUESTION_SUCCESS';
export const ADD_QUESTION_ERROR = 'ADD_QUESTION_ERROR';
export const SET_CATEGORIES = 'SET_CATEGORIES';