// questions
export const CONNECT_QUESTIONS_START = 'CONNECT_QUESTIONS_START';
export const ADD_QUESTION_INIT = 'ADD_QUESTION_INIT';
export const ADD_QUESTION_SUCCESS = 'ADD_QUESTION_SUCCESS';
export const ADD_QUESTION_ERROR = 'ADD_QUESTION_ERROR';
export const SEARCH_QUESTIONS_SUCCESS = 'SEARCH_QUESTIONS_SUCCESS';
export const SEARCH_QUESTIONS_ERROR = 'SEARCH_QUESTIONS_ERROR';
export const DELETE_QUESTION_SUCCESS = 'DELETE_QUESTION_SUCCESS';
export const DELETE_QUESTION_ERROR = 'DELETE_QUESTION_ERROR';

// categories
export const CONNECT_CATEGORIES_START = 'CONNECT_CATEGORIES_START';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_ERROR = 'FETCH_CATEGORIES_ERROR';
export const ADD_CATEGORY_SUCCESS = 'ADD_CATEGORY_SUCCESS';
export const ADD_CATEGORY_ERROR = 'ADD_CATEGORY_ERROR';
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';
export const DELETE_CATEGORY_ERROR = 'DELETE_CATEGORY_ERROR';

// competitions
export const CONNECT_COMPETITONS_START = 'CONNECT_COMPETITONS_START';
export const FETCH_COMPETITONS_SUCCESS = 'FETCH_COMPETITONS_SUCCESS';
export const FETCH_COMPETITONS_ERROR = 'FETCH_COMPETITONS_ERROR';
export const ADD_COMPETITION_SUCCESS = 'ADD_COMPETITION_SUCCESS';
export const ADD_COMPETITION_ERROR = 'ADD_COMPETITION_ERROR';
export const DELETE_COMPETITION_SUCCESS = 'DELETE_COMPETITION_SUCCESS';
export const DELETE_COMPETITION_ERROR = 'DELETE_COMPETITION_ERROR';

// tracks
export const CONNECT_TRACKS_START = 'CONNECT_TRACKS_START';
export const FETCH_TRACKS_SUCCESS = 'FETCH_TRACKS_SUCCESS';
export const FETCH_TRACKS_ERROR = 'FETCH_TRACKS_ERROR';
export const ADD_TRACK_SUCCESS = 'ADD_TRACK_SUCCESS';
export const ADD_TRACK_ERROR = 'ADD_TRACK_ERROR';
export const DELETE_TRACK_SUCCESS = 'DELETE_TRACK_SUCCESS';
export const DELETE_TRACK_ERROR = 'DELETE_TRACK_ERROR';

// results
export const CONNECT_RESULTS_START = 'CONNECT_RESULTS_START';
export const FETCH_RESULTS_SUCCESS = 'FETCH_RESULTS_SUCCESS';
export const FETCH_RESULTS_ERROR = 'FETCH_RESULTS_ERROR';